import { FoodItem, MicronutrientItem, WorkoutProgram } from "@/lib/types";

const demo = (query: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;

export const stubbornBellyFatKillerProgram: WorkoutProgram = {
  id: "stubborn-belly-fat-killer",
  title: "Stubborn Belly Fat Killer",
  subtitle: "Beginner fat-loss conditioning with simple strength moves",
  goal: "belly-fat-reduction",
  level: "beginner",
  targetDailyDeficit: 400,
  weeklyFatLossEstimateKg: "About 0.25-0.5 kg per week when paired with nutrition and recovery",
  safetyNote: "Avoid extreme calorie deficits. Beginners usually do best with a 300-500 calorie daily deficit, enough protein, sleep, and progressive training.",
  exercises: [
    {
      name: "Jumping Jacks",
      sets: 3,
      reps: "40 seconds",
      restSeconds: 30,
      tutorialUrl: demo("jumping jacks beginner form"),
      difficulty: "beginner",
      targetMuscles: ["Full body", "Calves", "Shoulders"],
      animationUrl: "",
      instructions: ["Stand tall with feet together", "Jump feet out while raising arms", "Return softly and keep a steady rhythm"],
      commonMistakes: ["Landing hard", "Holding breath", "Moving too fast before warmup"],
      beginnerTips: ["Step side to side instead of jumping if needed", "Keep knees soft"],
      metValue: 7.7,
      durationMinutesPerSet: 0.67
    },
    {
      name: "Mountain Climbers",
      sets: 3,
      reps: "30 seconds",
      restSeconds: 40,
      tutorialUrl: demo("mountain climbers beginner form"),
      difficulty: "moderate",
      targetMuscles: ["Core", "Shoulders", "Hip flexors"],
      animationUrl: "",
      instructions: ["Start in a strong plank", "Drive one knee toward the chest", "Alternate legs while keeping hips steady"],
      commonMistakes: ["Hips too high", "Shoulders drifting behind hands", "Rushing with poor control"],
      beginnerTips: ["Slow the pace and tap each foot forward", "Stop before your lower back sags"],
      metValue: 8,
      durationMinutesPerSet: 0.5
    },
    {
      name: "High Knees",
      sets: 3,
      reps: "30 seconds",
      restSeconds: 40,
      tutorialUrl: demo("high knees beginner low impact"),
      difficulty: "moderate",
      targetMuscles: ["Quads", "Core", "Calves"],
      animationUrl: "",
      instructions: ["Stand tall", "Lift knees toward hip height", "Pump arms and keep your torso upright"],
      commonMistakes: ["Leaning backward", "Landing stiff", "Letting knees collapse inward"],
      beginnerTips: ["March in place for a low-impact version", "Use a pace you can control"],
      metValue: 8,
      durationMinutesPerSet: 0.5
    },
    {
      name: "Plank",
      sets: 3,
      reps: "25 seconds",
      restSeconds: 35,
      tutorialUrl: demo("plank proper form beginner"),
      difficulty: "beginner",
      targetMuscles: ["Core", "Shoulders", "Glutes"],
      animationUrl: "",
      instructions: ["Place elbows under shoulders", "Brace your core", "Keep head, ribs, hips, and heels aligned"],
      commonMistakes: ["Hips sagging", "Holding breath", "Shrugging shoulders"],
      beginnerTips: ["Use knees-down plank if needed", "Think ribs down and glutes gently squeezed"],
      metValue: 3.3,
      durationMinutesPerSet: 0.42
    },
    {
      name: "Bicycle Crunches",
      sets: 3,
      reps: "10 each side",
      restSeconds: 35,
      tutorialUrl: demo("bicycle crunch beginner form"),
      difficulty: "beginner",
      targetMuscles: ["Abs", "Obliques"],
      animationUrl: "",
      instructions: ["Lie on your back with hands light behind head", "Rotate shoulder toward opposite knee", "Move slowly and alternate sides"],
      commonMistakes: ["Pulling the neck", "Rushing reps", "Arching lower back"],
      beginnerTips: ["Keep elbows wide", "Shorten the range until control improves"],
      metValue: 4,
      durationMinutesPerSet: 0.8
    },
    {
      name: "Bodyweight Squats",
      sets: 3,
      reps: "12 reps",
      restSeconds: 45,
      tutorialUrl: demo("bodyweight squat proper form beginner"),
      difficulty: "beginner",
      targetMuscles: ["Quads", "Glutes", "Hamstrings"],
      animationUrl: "",
      instructions: ["Stand feet about shoulder width", "Sit hips back and down", "Drive through the full foot to stand"],
      commonMistakes: ["Knees caving inward", "Heels lifting", "Dropping too fast"],
      beginnerTips: ["Use a chair as a target", "Keep chest proud and ribs stacked"],
      metValue: 5,
      durationMinutesPerSet: 0.75
    },
    {
      name: "Burpees beginner version",
      sets: 2,
      reps: "6 reps",
      restSeconds: 60,
      tutorialUrl: demo("beginner burpee step back no push up"),
      difficulty: "challenging",
      targetMuscles: ["Full body", "Chest", "Legs", "Core"],
      animationUrl: "",
      instructions: ["Squat and place hands down", "Step back to plank", "Step feet forward and stand tall"],
      commonMistakes: ["Collapsing into plank", "Holding breath", "Jumping before ready"],
      beginnerTips: ["Skip the jump and push-up", "Use a bench for elevated hands"],
      metValue: 8,
      durationMinutesPerSet: 0.9
    },
    {
      name: "Leg Raises beginner version",
      sets: 3,
      reps: "8 reps",
      restSeconds: 40,
      tutorialUrl: demo("beginner leg raises bent knee form"),
      difficulty: "beginner",
      targetMuscles: ["Lower abs", "Hip flexors"],
      animationUrl: "",
      instructions: ["Lie on your back", "Keep knees slightly bent", "Lower legs only as far as your back stays flat"],
      commonMistakes: ["Lower back arching", "Swinging legs", "Holding breath"],
      beginnerTips: ["Bend knees more to reduce difficulty", "Place hands under hips if comfortable"],
      metValue: 3.8,
      durationMinutesPerSet: 0.65
    },
    {
      name: "Russian Twists beginner version",
      sets: 3,
      reps: "12 total",
      restSeconds: 35,
      tutorialUrl: demo("beginner russian twist feet down"),
      difficulty: "beginner",
      targetMuscles: ["Obliques", "Abs"],
      animationUrl: "",
      instructions: ["Sit tall with feet down", "Lean back slightly", "Rotate ribs side to side with control"],
      commonMistakes: ["Only moving the arms", "Rounding the back", "Going too fast"],
      beginnerTips: ["Keep feet on the floor", "Use no weight at first"],
      metValue: 3.8,
      durationMinutesPerSet: 0.65
    },
    {
      name: "Glute Bridges",
      sets: 3,
      reps: "12 reps",
      restSeconds: 35,
      tutorialUrl: demo("glute bridge proper form beginner"),
      difficulty: "beginner",
      targetMuscles: ["Glutes", "Hamstrings", "Core"],
      animationUrl: "",
      instructions: ["Lie on your back with knees bent", "Drive through heels", "Lift hips and squeeze glutes at the top"],
      commonMistakes: ["Overarching lower back", "Pushing through toes", "Rushing reps"],
      beginnerTips: ["Pause one second at the top", "Keep ribs down"],
      metValue: 3.5,
      durationMinutesPerSet: 0.7
    }
  ]
};

export const nutritionFoods: FoodItem[] = [
  { name: "Chicken breast", category: "protein", serving: "120g cooked", calories: 198, protein: 37, carbs: 0, fats: 4, keyMicronutrients: ["B12", "Zinc"], fitnessBenefit: "Lean protein supports muscle repair and fullness.", mealUse: "Add to rice bowls, salads, wraps, or meal prep boxes." },
  { name: "Eggs", category: "protein", serving: "2 large", calories: 144, protein: 12, carbs: 1, fats: 10, keyMicronutrients: ["Vitamin D", "B12", "Choline"], fitnessBenefit: "Complete protein and fats help steady energy.", mealUse: "Use in omelets, toast plates, or snack boxes." },
  { name: "Greek yogurt", category: "protein", serving: "200g plain", calories: 146, protein: 20, carbs: 8, fats: 4, keyMicronutrients: ["Calcium", "B12"], fitnessBenefit: "High protein option that is easy after training.", mealUse: "Top with berries, oats, or chia seeds." },
  { name: "Tuna", category: "protein", serving: "1 can drained", calories: 132, protein: 29, carbs: 0, fats: 1, keyMicronutrients: ["B12", "Omega-3"], fitnessBenefit: "Convenient lean protein for calorie control.", mealUse: "Use in sandwiches, rice bowls, or salads." },
  { name: "Salmon", category: "protein", serving: "120g cooked", calories: 247, protein: 28, carbs: 0, fats: 14, keyMicronutrients: ["Vitamin D", "Omega-3", "Potassium"], fitnessBenefit: "Protein plus omega-3 fats support recovery.", mealUse: "Pair with potatoes and vegetables." },
  { name: "Tofu", category: "protein", serving: "150g firm", calories: 180, protein: 19, carbs: 4, fats: 11, keyMicronutrients: ["Calcium", "Iron"], fitnessBenefit: "Plant protein with minerals for vegetarian plans.", mealUse: "Use in stir-fries, bowls, or curries." },
  { name: "Lentils", category: "protein", serving: "1 cup cooked", calories: 230, protein: 18, carbs: 40, fats: 1, keyMicronutrients: ["Iron", "Magnesium", "Potassium"], fitnessBenefit: "Protein and fiber support fullness.", mealUse: "Add to soups, stews, salads, or wraps." },
  { name: "Cottage cheese", category: "protein", serving: "200g", calories: 164, protein: 24, carbs: 7, fats: 4, keyMicronutrients: ["Calcium", "B12"], fitnessBenefit: "Slow-digesting protein helps satiety.", mealUse: "Eat with fruit or add to toast bowls." },
  { name: "Oats", category: "carbs", serving: "50g dry", calories: 190, protein: 6, carbs: 32, fats: 4, keyMicronutrients: ["Magnesium", "Iron"], fitnessBenefit: "Slow carbs fuel workouts and keep hunger steadier.", mealUse: "Use for overnight oats or warm porridge." },
  { name: "Rice", category: "carbs", serving: "1 cup cooked", calories: 205, protein: 4, carbs: 45, fats: 0, keyMicronutrients: ["Magnesium"], fitnessBenefit: "Easy training fuel and meal prep base.", mealUse: "Pair with lean protein and vegetables." },
  { name: "Sweet potato", category: "carbs", serving: "1 medium", calories: 112, protein: 2, carbs: 26, fats: 0, keyMicronutrients: ["Vitamin A", "Potassium"], fitnessBenefit: "Carbs plus potassium support training energy.", mealUse: "Roast for bowls or side dishes." },
  { name: "Quinoa", category: "carbs", serving: "1 cup cooked", calories: 222, protein: 8, carbs: 39, fats: 4, keyMicronutrients: ["Magnesium", "Iron", "Zinc"], fitnessBenefit: "Carbs with extra protein and minerals.", mealUse: "Use in salads or power bowls." },
  { name: "Banana", category: "carbs", serving: "1 medium", calories: 105, protein: 1, carbs: 27, fats: 0, keyMicronutrients: ["Potassium", "Vitamin C"], fitnessBenefit: "Quick pre-workout carbohydrate.", mealUse: "Eat before training or add to yogurt." },
  { name: "Wholegrain bread", category: "carbs", serving: "2 slices", calories: 180, protein: 8, carbs: 32, fats: 3, keyMicronutrients: ["Iron", "Magnesium"], fitnessBenefit: "Convenient carbs with fiber.", mealUse: "Use for egg, tuna, or cottage cheese toast." },
  { name: "Potatoes", category: "carbs", serving: "250g boiled", calories: 193, protein: 5, carbs: 44, fats: 0, keyMicronutrients: ["Potassium", "Vitamin C"], fitnessBenefit: "Filling carb source for fat-loss meals.", mealUse: "Serve with fish, chicken, or tofu." },
  { name: "Avocado", category: "healthy-fats", serving: "1/2 medium", calories: 120, protein: 2, carbs: 6, fats: 11, keyMicronutrients: ["Potassium", "Magnesium"], fitnessBenefit: "Healthy fats add satisfaction to meals.", mealUse: "Add to toast, bowls, or salads." },
  { name: "Olive oil", category: "healthy-fats", serving: "1 tbsp", calories: 119, protein: 0, carbs: 0, fats: 14, keyMicronutrients: ["Vitamin E"], fitnessBenefit: "Calorie-dense fat useful in controlled portions.", mealUse: "Use as a salad dressing or cooking fat." },
  { name: "Nuts", category: "healthy-fats", serving: "30g", calories: 180, protein: 6, carbs: 6, fats: 15, keyMicronutrients: ["Magnesium", "Zinc"], fitnessBenefit: "Portable fats and minerals for balanced snacks.", mealUse: "Portion into snack packs or add to yogurt." },
  { name: "Peanut butter", category: "healthy-fats", serving: "1 tbsp", calories: 95, protein: 4, carbs: 3, fats: 8, keyMicronutrients: ["Magnesium"], fitnessBenefit: "Adds fats and flavor, best measured for fat loss.", mealUse: "Spread on toast or add to oats." },
  { name: "Chia seeds", category: "healthy-fats", serving: "1 tbsp", calories: 58, protein: 2, carbs: 5, fats: 4, keyMicronutrients: ["Omega-3", "Calcium", "Magnesium"], fitnessBenefit: "Fiber and fats help meals feel more filling.", mealUse: "Stir into yogurt, oats, or smoothies." }
];

export const micronutrients: MicronutrientItem[] = [
  { name: "Vitamin A", foods: ["Sweet potato", "Eggs"], whyItMatters: "Supports immune health and vision." },
  { name: "Vitamin B12", foods: ["Eggs", "Greek yogurt", "Tuna", "Salmon"], whyItMatters: "Supports energy metabolism and red blood cells." },
  { name: "Vitamin C", foods: ["Banana", "Potatoes"], whyItMatters: "Supports tissue repair and iron absorption." },
  { name: "Vitamin D", foods: ["Eggs", "Salmon"], whyItMatters: "Supports bones, muscles, and immune function." },
  { name: "Iron", foods: ["Lentils", "Tofu", "Oats", "Quinoa"], whyItMatters: "Helps transport oxygen for training capacity." },
  { name: "Magnesium", foods: ["Oats", "Quinoa", "Nuts", "Chia seeds"], whyItMatters: "Supports muscle and nerve function." },
  { name: "Zinc", foods: ["Chicken breast", "Quinoa", "Nuts"], whyItMatters: "Supports recovery and immune health." },
  { name: "Potassium", foods: ["Banana", "Sweet potato", "Potatoes", "Avocado"], whyItMatters: "Supports hydration and muscle contraction." },
  { name: "Calcium", foods: ["Greek yogurt", "Cottage cheese", "Tofu", "Chia seeds"], whyItMatters: "Supports bones and muscle contraction." },
  { name: "Omega-3", foods: ["Salmon", "Tuna", "Chia seeds"], whyItMatters: "Supports heart health and recovery." }
];
