import { FitnessVideo, VideoCategory } from "@/lib/types";

const demoVideoFiles = [
  "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm"
];

const supplementalMajorCategoryVideos: FitnessVideo[] = [
  video({
    id: "full-body-strength-flow",
    title: "Full-body strength flow",
    category: "Full body",
    bodyPart: "Total body",
    difficulty: "intermediate",
    durationSeconds: 540,
    thumbnailUrl: thumb("1517836357463-d25dfeac3438"),
    videoUrl: nativeVideo("full body strength workout exercise demonstration"),
    coachName: "Coach Eli",
    tags: ["full body", "strength", "form"],
    targetMuscles: ["legs", "chest", "back", "core"],
    caloriesEstimate: 110,
    coachTips: ["Keep reps smooth", "Rest before form drops"],
    safetyNotes: ["Use easier variations for any painful movement"],
    likeCount: 980
  }),
  video({
    id: "chest-knee-pushup",
    title: "Knee push-up form tutorial",
    category: "Chest",
    bodyPart: "Chest",
    difficulty: "beginner",
    durationSeconds: 50,
    thumbnailUrl: thumb("1598971639058-fab3c3109a00"),
    videoUrl: nativeVideo("knee push up proper form beginner"),
    coachName: "Coach Maya",
    tags: ["chest", "push-up", "beginner"],
    targetMuscles: ["chest", "triceps", "shoulders"],
    caloriesEstimate: 10,
    coachTips: ["Brace before lowering", "Keep elbows about 45 degrees"],
    safetyNotes: ["Use incline push-ups if wrists feel sore"],
    likeCount: 720
  }),
  video({
    id: "chest-floor-press",
    title: "Dumbbell floor press basics",
    category: "Chest",
    bodyPart: "Chest",
    difficulty: "intermediate",
    durationSeconds: 70,
    thumbnailUrl: thumb("1581009137042-c552e485697a"),
    videoUrl: nativeVideo("dumbbell floor press proper form"),
    coachName: "Coach Dan",
    tags: ["chest", "dumbbells", "strength"],
    targetMuscles: ["chest", "triceps", "front shoulders"],
    caloriesEstimate: 14,
    coachTips: ["Pause elbows gently on the floor", "Press without shrugging"],
    safetyNotes: ["Choose a weight you can control"],
    likeCount: 640
  }),
  video({
    id: "back-row-demo",
    title: "One-arm row form demo",
    category: "Back",
    bodyPart: "Back",
    difficulty: "beginner",
    durationSeconds: 60,
    thumbnailUrl: thumb("1534367610401-9f5ed68180aa"),
    videoUrl: nativeVideo("one arm dumbbell row proper form"),
    coachName: "Coach Eli",
    tags: ["back", "row", "posture"],
    targetMuscles: ["lats", "upper back", "biceps"],
    caloriesEstimate: 12,
    coachTips: ["Pull elbow toward hip", "Keep neck relaxed"],
    safetyNotes: ["Avoid twisting the torso"],
    likeCount: 690
  }),
  video({
    id: "back-band-row",
    title: "Band row posture fix",
    category: "Back",
    bodyPart: "Back",
    difficulty: "beginner",
    durationSeconds: 48,
    thumbnailUrl: thumb("1518611012118-696072aa579a"),
    videoUrl: nativeVideo("resistance band row proper form posture"),
    coachName: "Coach Noor",
    tags: ["back", "band", "home workout"],
    targetMuscles: ["lats", "rhomboids", "rear delts"],
    caloriesEstimate: 10,
    coachTips: ["Squeeze shoulder blades lightly", "Do not lean back to cheat reps"],
    safetyNotes: ["Anchor the band securely"],
    likeCount: 610
  }),
  video({
    id: "back-bird-dog",
    title: "Bird dog for back-friendly core",
    category: "Back",
    bodyPart: "Back + core",
    difficulty: "beginner",
    durationSeconds: 55,
    thumbnailUrl: thumb("1552196563-55cd4e45efb3"),
    videoUrl: nativeVideo("bird dog exercise proper form"),
    coachName: "Coach Dan",
    tags: ["back", "core", "stability"],
    targetMuscles: ["lower back", "glutes", "deep core"],
    caloriesEstimate: 8,
    coachTips: ["Reach long", "Keep hips square"],
    safetyNotes: ["Use a small range first"],
    relatedExerciseId: "bird-dog",
    likeCount: 830
  }),
  video({
    id: "shoulders-press-demo",
    title: "Shoulder press without rib flare",
    category: "Shoulders",
    bodyPart: "Shoulders",
    difficulty: "intermediate",
    durationSeconds: 62,
    thumbnailUrl: thumb("1581009137042-c552e485697a"),
    videoUrl: nativeVideo("dumbbell shoulder press proper form rib flare"),
    coachName: "Coach Maya",
    tags: ["shoulders", "press", "form"],
    targetMuscles: ["shoulders", "triceps", "core"],
    caloriesEstimate: 12,
    coachTips: ["Lock ribs down", "Press slightly back, not forward"],
    safetyNotes: ["Stop if shoulder pinches"],
    likeCount: 700
  }),
  video({
    id: "shoulders-lateral-raise",
    title: "Lateral raise: no swinging",
    category: "Shoulders",
    bodyPart: "Shoulders",
    difficulty: "beginner",
    durationSeconds: 45,
    thumbnailUrl: thumb("1583454110551-21f2fa2afe61"),
    videoUrl: nativeVideo("lateral raise proper form no swinging"),
    coachName: "Coach Jay",
    tags: ["shoulders", "lateral raise", "dumbbells"],
    targetMuscles: ["side delts", "upper back"],
    caloriesEstimate: 8,
    coachTips: ["Lead with elbows", "Use lighter weight than you think"],
    safetyNotes: ["Avoid shrugging through the neck"],
    likeCount: 580
  }),
  video({
    id: "shoulders-scapular-control",
    title: "Shoulder blade control drill",
    category: "Shoulders",
    bodyPart: "Shoulders",
    difficulty: "beginner",
    durationSeconds: 50,
    thumbnailUrl: thumb("1552196563-55cd4e45efb3"),
    videoUrl: nativeVideo("scapular wall slides shoulder mobility proper form"),
    coachName: "Coach Noor",
    tags: ["shoulders", "mobility", "posture"],
    targetMuscles: ["shoulders", "upper back", "serratus"],
    caloriesEstimate: 6,
    coachTips: ["Move slowly", "Keep ribs from flaring"],
    safetyNotes: ["Stay in a pain-free range"],
    likeCount: 540
  }),
  video({
    id: "arms-biceps-curl",
    title: "Biceps curl without swinging",
    category: "Arms",
    bodyPart: "Arms",
    difficulty: "beginner",
    durationSeconds: 48,
    thumbnailUrl: thumb("1583454110551-21f2fa2afe61"),
    videoUrl: nativeVideo("biceps curl proper form no swinging"),
    coachName: "Coach Jay",
    tags: ["arms", "biceps", "dumbbells"],
    targetMuscles: ["biceps", "forearms"],
    caloriesEstimate: 7,
    coachTips: ["Keep elbows quiet", "Lower slowly"],
    safetyNotes: ["Reduce weight if your back arches"],
    likeCount: 690
  }),
  video({
    id: "arms-triceps-extension",
    title: "Triceps extension elbow position",
    category: "Arms",
    bodyPart: "Arms",
    difficulty: "beginner",
    durationSeconds: 45,
    thumbnailUrl: thumb("1583454110551-21f2fa2afe61"),
    videoUrl: nativeVideo("triceps extension proper form elbow position"),
    coachName: "Coach Maya",
    tags: ["arms", "triceps", "form"],
    targetMuscles: ["triceps", "shoulders"],
    caloriesEstimate: 8,
    coachTips: ["Point elbows forward", "Move only the forearms"],
    safetyNotes: ["Avoid if elbows feel sharp pain"],
    likeCount: 620
  }),
  video({
    id: "arms-chair-dip",
    title: "Bench dip safety check",
    category: "Arms",
    bodyPart: "Arms",
    difficulty: "intermediate",
    durationSeconds: 52,
    thumbnailUrl: thumb("1517836357463-d25dfeac3438"),
    videoUrl: nativeVideo("bench dip proper form shoulder safety"),
    coachName: "Coach Eli",
    tags: ["arms", "triceps", "mistakes"],
    targetMuscles: ["triceps", "chest", "shoulders"],
    caloriesEstimate: 10,
    coachTips: ["Keep shoulders away from ears", "Use a small range first"],
    safetyNotes: ["Skip dips if shoulders feel pinchy"],
    likeCount: 520
  }),
  video({
    id: "glutes-clamshell",
    title: "Clamshell glute activation",
    category: "Glutes",
    bodyPart: "Glutes",
    difficulty: "beginner",
    durationSeconds: 50,
    thumbnailUrl: thumb("1571019613454-1cb2f99b2d8b"),
    videoUrl: nativeVideo("clamshell exercise glute activation proper form"),
    coachName: "Coach Noor",
    tags: ["glutes", "activation", "hips"],
    targetMuscles: ["glute medius", "hips"],
    caloriesEstimate: 7,
    coachTips: ["Keep hips stacked", "Pause at the top"],
    safetyNotes: ["Do not roll backward to fake range"],
    likeCount: 720
  }),
  video({
    id: "glutes-hip-thrust",
    title: "Hip thrust setup basics",
    category: "Glutes",
    bodyPart: "Glutes",
    difficulty: "intermediate",
    durationSeconds: 70,
    thumbnailUrl: thumb("1571019613454-1cb2f99b2d8b"),
    videoUrl: nativeVideo("hip thrust proper form glutes"),
    coachName: "Coach Maya",
    tags: ["glutes", "hip thrust", "strength"],
    targetMuscles: ["glutes", "hamstrings"],
    caloriesEstimate: 14,
    coachTips: ["Ribs down at lockout", "Shins vertical near the top"],
    safetyNotes: ["Pad the hips and use controlled load"],
    likeCount: 1010
  }),
  video({
    id: "cardio-jumping-jacks",
    title: "Jumping jacks low-impact option",
    category: "Cardio",
    bodyPart: "Cardio",
    difficulty: "beginner",
    durationSeconds: 42,
    thumbnailUrl: thumb("1518611012118-696072aa579a"),
    videoUrl: nativeVideo("jumping jacks proper form low impact step jack"),
    coachName: "Coach Dan",
    tags: ["cardio", "jumping jacks", "low impact"],
    targetMuscles: ["calves", "shoulders", "heart"],
    caloriesEstimate: 18,
    coachTips: ["Land softly", "Step side to side if jumping is too much"],
    safetyNotes: ["Choose low impact for knee or ankle sensitivity"],
    likeCount: 850
  }),
  video({
    id: "mobility-spine-flow",
    title: "Spine mobility flow",
    category: "Mobility",
    bodyPart: "Spine",
    difficulty: "beginner",
    durationSeconds: 180,
    thumbnailUrl: thumb("1552196563-55cd4e45efb3"),
    videoUrl: nativeVideo("spine mobility flow cat cow thoracic rotation beginner"),
    coachName: "Coach Eli",
    tags: ["mobility", "spine", "recovery"],
    targetMuscles: ["spine", "upper back", "hips"],
    caloriesEstimate: 10,
    coachTips: ["Move slowly", "Exhale into the stretch"],
    safetyNotes: ["Stay away from sharp pain"],
    likeCount: 760
  }),
  video({
    id: "mobility-ankles-squat",
    title: "Ankle mobility for better squats",
    category: "Mobility",
    bodyPart: "Ankles",
    difficulty: "beginner",
    durationSeconds: 150,
    thumbnailUrl: thumb("1552196563-55cd4e45efb3"),
    videoUrl: nativeVideo("ankle mobility for squat beginner"),
    coachName: "Coach Noor",
    tags: ["mobility", "ankles", "squat"],
    targetMuscles: ["ankles", "calves", "feet"],
    caloriesEstimate: 8,
    coachTips: ["Keep heel down", "Use small daily doses"],
    safetyNotes: ["Do not force range through pinching"],
    likeCount: 640
  }),
  video({
    id: "beginner-warmup",
    title: "5-minute beginner warm-up",
    category: "Beginner tips",
    bodyPart: "Full body",
    difficulty: "beginner",
    durationSeconds: 300,
    thumbnailUrl: thumb("1518611012118-696072aa579a"),
    videoUrl: nativeVideo("5 minute beginner warm up full body no equipment"),
    coachName: "Coach Jay",
    tags: ["beginner", "warm-up", "no equipment"],
    targetMuscles: ["full body", "hips", "shoulders"],
    caloriesEstimate: 25,
    coachTips: ["Warm up joints first", "Start easier than you think"],
    safetyNotes: ["Do not sprint cold"],
    likeCount: 930
  }),
  video({
    id: "diet-snack-swap",
    title: "Snack swaps for fat loss",
    category: "Diet tips",
    bodyPart: "Nutrition",
    difficulty: "beginner",
    durationSeconds: 55,
    thumbnailUrl: thumb("1490645935967-10de6ba17061"),
    videoUrl: nativeVideo("healthy snack swaps for fat loss protein fiber"),
    coachName: "Coach Maya",
    tags: ["diet tips", "snacks", "fat loss"],
    targetMuscles: ["nutrition"],
    caloriesEstimate: 0,
    coachTips: ["Pair protein with fibre", "Plan snacks before hunger spikes"],
    safetyNotes: ["Do not under-eat to compensate for one snack"],
    likeCount: 1180
  }),
  video({
    id: "legs-wall-sit",
    title: "Wall sit: leg endurance setup",
    category: "Legs",
    bodyPart: "Legs",
    difficulty: "beginner",
    durationSeconds: 45,
    thumbnailUrl: thumb("1534438327276-14e5300c3a48"),
    videoUrl: nativeVideo("wall sit proper form beginner"),
    coachName: "Coach Dan",
    tags: ["legs", "wall sit", "endurance"],
    targetMuscles: ["quads", "glutes", "core"],
    caloriesEstimate: 9,
    coachTips: ["Back stays flat on the wall", "Hold a height you can breathe through"],
    safetyNotes: ["Stand up if knee pain appears"],
    relatedExerciseId: "wall-sit",
    likeCount: 590
  })
];

function nativeVideo(seed: string) {
  const index = seed.split("").reduce((sum, char) => sum + char.charCodeAt(0), 0) % demoVideoFiles.length;
  return demoVideoFiles[index];
}

function thumb(seed: string) {
  return `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=900&q=80`;
}

export const videoCategories: VideoCategory[] = [
  "Full body",
  "Abs / core",
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Legs",
  "Glutes",
  "Cardio",
  "Mobility",
  "Beginner tips",
  "Diet tips",
  "Protein tips",
  "Hydration tips",
  "Recovery"
];

function video(input: FitnessVideo): FitnessVideo {
  return input;
}

export const fitnessVideos: FitnessVideo[] = [
  video({
    id: "demo-bodyweight-squat",
    title: "Bodyweight squat: clean reps only",
    category: "Legs",
    bodyPart: "Legs",
    difficulty: "beginner",
    durationSeconds: 70,
    thumbnailUrl: thumb("1534438327276-14e5300c3a48"),
    videoUrl: nativeVideo("bodyweight squat proper form beginner demonstration"),
    coachName: "Coach Noor",
    tags: ["exercise demo", "squat", "legs", "beginner"],
    targetMuscles: ["quads", "glutes", "hamstrings", "core"],
    caloriesEstimate: 18,
    coachTips: ["Keep heels heavy", "Track knees in line with toes", "Use a chair target if depth feels messy"],
    safetyNotes: ["Use pain-free depth", "Slow down if knees cave inward"],
    relatedExerciseId: "bodyweight-squat",
    likeCount: 1380
  }),
  video({
    id: "demo-plank",
    title: "Plank setup: ribs down, glutes on",
    category: "Abs / core",
    bodyPart: "Core",
    difficulty: "beginner",
    durationSeconds: 55,
    thumbnailUrl: thumb("1517964603305-11c0f6f66012"),
    videoUrl: nativeVideo("plank proper form beginner demonstration"),
    coachName: "Coach Dan",
    tags: ["exercise demo", "plank", "core", "form"],
    targetMuscles: ["abs", "deep core", "shoulders", "glutes"],
    caloriesEstimate: 8,
    coachTips: ["Elbows under shoulders", "Breathe through the hold", "End the set before your hips sag"],
    safetyNotes: ["Drop to knees if your lower back feels loaded"],
    relatedExerciseId: "plank",
    likeCount: 940
  }),
  video({
    id: "demo-mountain-climbers",
    title: "Mountain climbers without hip bounce",
    category: "Full body",
    bodyPart: "Core + cardio",
    difficulty: "intermediate",
    durationSeconds: 60,
    thumbnailUrl: thumb("1518611012118-696072aa579a"),
    videoUrl: nativeVideo("mountain climbers proper form demonstration"),
    coachName: "Coach Maya",
    tags: ["exercise demo", "cardio", "core", "fat loss"],
    targetMuscles: ["core", "shoulders", "hip flexors", "legs"],
    caloriesEstimate: 32,
    coachTips: ["Stack shoulders over wrists", "Keep hips quiet", "Step instead of running if form breaks"],
    safetyNotes: ["Use an incline if wrists or lower back feel stressed"],
    relatedExerciseId: "mountain-climbers",
    likeCount: 1510
  }),
  video({
    id: "demo-glute-bridge",
    title: "Glute bridge: feel glutes, not back",
    category: "Glutes",
    bodyPart: "Glutes",
    difficulty: "beginner",
    durationSeconds: 58,
    thumbnailUrl: thumb("1571019613454-1cb2f99b2d8b"),
    videoUrl: nativeVideo("glute bridge proper form beginner demonstration"),
    coachName: "Coach Dan",
    tags: ["exercise demo", "glutes", "bridge", "back friendly"],
    targetMuscles: ["glutes", "hamstrings", "core"],
    caloriesEstimate: 10,
    coachTips: ["Drive through heels", "Keep ribs down", "Pause briefly at the top"],
    safetyNotes: ["Do not arch your lower back to lift higher"],
    relatedExerciseId: "glute-bridge",
    likeCount: 1190
  }),
  video({
    id: "demo-push-up-incline",
    title: "Incline push-up for your first push-up",
    category: "Chest",
    bodyPart: "Chest",
    difficulty: "beginner",
    durationSeconds: 65,
    thumbnailUrl: thumb("1598971639058-fab3c3109a00"),
    videoUrl: nativeVideo("incline push up beginner form demonstration"),
    coachName: "Coach Eli",
    tags: ["exercise demo", "push-up", "chest", "beginner strength"],
    targetMuscles: ["chest", "triceps", "shoulders", "core"],
    caloriesEstimate: 14,
    coachTips: ["Brace like a plank", "Use a high surface first", "Lower chest and hips together"],
    safetyNotes: ["Elevate hands if wrists or shoulders feel uncomfortable"],
    relatedExerciseId: "push-up",
    likeCount: 1010
  }),
  video({
    id: "demo-reverse-lunge",
    title: "Reverse lunge: knee-friendly setup",
    category: "Legs",
    bodyPart: "Legs",
    difficulty: "intermediate",
    durationSeconds: 68,
    thumbnailUrl: thumb("1549060279-7e168fcee0c2"),
    videoUrl: nativeVideo("reverse lunge proper form beginner demonstration"),
    coachName: "Coach Noor",
    tags: ["exercise demo", "lunge", "legs", "glutes"],
    targetMuscles: ["quads", "glutes", "hamstrings", "core"],
    caloriesEstimate: 20,
    coachTips: ["Step back long enough", "Keep front heel grounded", "Use support while learning balance"],
    safetyNotes: ["Shorten range if knees feel irritated"],
    relatedExerciseId: "reverse-lunge",
    likeCount: 870
  }),
  video({
    id: "form-squat-mistakes",
    title: "3 squat mistakes beginners make",
    category: "Beginner tips",
    bodyPart: "Legs",
    difficulty: "beginner",
    durationSeconds: 50,
    thumbnailUrl: thumb("1517836357463-d25dfeac3438"),
    videoUrl: nativeVideo("common squat mistakes beginners knees cave heels lift"),
    coachName: "Coach Maya",
    tags: ["common mistakes", "squat", "form tutorial"],
    targetMuscles: ["quads", "glutes", "core"],
    caloriesEstimate: 8,
    coachTips: ["Watch knees, heels, and tempo first", "Perfect reps beat more reps"],
    safetyNotes: ["Do not force deep range if your back rounds"],
    relatedExerciseId: "bodyweight-squat",
    likeCount: 1720
  }),
  video({
    id: "form-plank-mistakes",
    title: "Fix plank sag in 30 seconds",
    category: "Abs / core",
    bodyPart: "Core",
    difficulty: "beginner",
    durationSeconds: 42,
    thumbnailUrl: thumb("1517964603305-11c0f6f66012"),
    videoUrl: nativeVideo("plank common mistakes hips sag beginner fix"),
    coachName: "Coach Dan",
    tags: ["common mistakes", "plank", "core"],
    targetMuscles: ["abs", "shoulders", "glutes"],
    caloriesEstimate: 6,
    coachTips: ["Squeeze glutes", "Tuck ribs", "Shorter perfect holds work better"],
    safetyNotes: ["Switch to knees-down plank if low back takes over"],
    relatedExerciseId: "plank",
    likeCount: 1460
  }),
  video({
    id: "form-leg-raise-back",
    title: "Leg raises without lower-back arch",
    category: "Abs / core",
    bodyPart: "Lower abs",
    difficulty: "beginner",
    durationSeconds: 60,
    thumbnailUrl: thumb("1518459031867-a89b944bffe4"),
    videoUrl: nativeVideo("leg raise lower back arch fix beginner"),
    coachName: "Coach Eli",
    tags: ["form tutorial", "lower abs", "core"],
    targetMuscles: ["lower abs", "hip flexors", "deep core"],
    caloriesEstimate: 10,
    coachTips: ["Bend knees first", "Only lower as far as your back stays flat"],
    safetyNotes: ["Choose dead bugs if leg raises irritate your back"],
    relatedExerciseId: "leg-raises",
    likeCount: 780
  }),
  video({
    id: "belly-fat-total-loss",
    title: "Belly fat reduces through total fat loss",
    category: "Diet tips",
    bodyPart: "Nutrition",
    difficulty: "beginner",
    durationSeconds: 48,
    thumbnailUrl: thumb("1490645935967-10de6ba17061"),
    videoUrl: nativeVideo("belly fat spot reduction myth calorie deficit strength cardio sleep"),
    coachName: "Coach Noor",
    tags: ["belly fat", "fat loss", "no spot reduction", "calorie deficit"],
    targetMuscles: ["total body"],
    caloriesEstimate: 0,
    coachTips: ["Pair a small calorie deficit with strength, cardio, protein, sleep, and steps"],
    safetyNotes: ["Avoid extreme deficits and crash diets"],
    likeCount: 3200
  }),
  video({
    id: "belly-fat-low-impact-workout",
    title: "Low-impact belly-fat workout",
    category: "Full body",
    bodyPart: "Total body",
    difficulty: "beginner",
    durationSeconds: 720,
    thumbnailUrl: thumb("1518611012118-696072aa579a"),
    videoUrl: nativeVideo("low impact fat loss workout beginner no jumping"),
    coachName: "Coach Maya",
    tags: ["belly fat", "fat loss", "low impact", "beginner workout"],
    targetMuscles: ["legs", "glutes", "core", "shoulders"],
    caloriesEstimate: 95,
    coachTips: ["Keep intensity at 6-7 out of 10", "Use step variations if jumping feels rough"],
    safetyNotes: ["Stop if dizzy; hydrate and rest as needed"],
    relatedExerciseId: "low-impact-hiit",
    likeCount: 2870
  }),
  video({
    id: "belly-fat-core-cardio",
    title: "Core + cardio fat-loss circuit",
    category: "Cardio",
    bodyPart: "Core + cardio",
    difficulty: "intermediate",
    durationSeconds: 900,
    thumbnailUrl: thumb("1571902943202-507ec2618e8f"),
    videoUrl: nativeVideo("core cardio fat loss workout no equipment"),
    coachName: "Coach Jay",
    tags: ["belly fat", "core", "cardio", "circuit"],
    targetMuscles: ["core", "legs", "shoulders", "heart"],
    caloriesEstimate: 150,
    coachTips: ["Move with control before speed", "Rest 30-45 seconds between rounds"],
    safetyNotes: ["Modify mountain climbers to an incline if wrists fatigue"],
    relatedExerciseId: "mountain-climbers",
    likeCount: 2240
  }),
  video({
    id: "plan-beginner-7-day",
    title: "Beginner 7-day training plan",
    category: "Beginner tips",
    bodyPart: "Full plan",
    difficulty: "beginner",
    durationSeconds: 90,
    thumbnailUrl: thumb("1534438327276-14e5300c3a48"),
    videoUrl: nativeVideo("beginner 7 day workout plan strength cardio mobility"),
    coachName: "Coach Dan",
    tags: ["beginner plan", "weekly plan", "strength", "cardio"],
    targetMuscles: ["full body"],
    caloriesEstimate: 0,
    coachTips: ["Train 3 strength days, 2 cardio days, 2 recovery days", "Repeat the week before progressing"],
    safetyNotes: ["Leave one or two reps in reserve on strength exercises"],
    likeCount: 1930
  }),
  video({
    id: "plan-intermediate-4-day",
    title: "Intermediate 4-day strength split",
    category: "Full body",
    bodyPart: "Full plan",
    difficulty: "intermediate",
    durationSeconds: 110,
    thumbnailUrl: thumb("1517836357463-d25dfeac3438"),
    videoUrl: nativeVideo("intermediate 4 day workout split upper lower full body cardio"),
    coachName: "Coach Eli",
    tags: ["intermediate plan", "upper lower", "progressive overload"],
    targetMuscles: ["chest", "back", "legs", "glutes", "core"],
    caloriesEstimate: 0,
    coachTips: ["Progress reps first, then load", "Keep cardio mostly Zone 2 unless recovery is strong"],
    safetyNotes: ["Deload if soreness or performance drops for several sessions"],
    likeCount: 1510
  }),
  video({
    id: "plan-advanced-conditioning",
    title: "Advanced conditioning week",
    category: "Cardio",
    bodyPart: "Full plan",
    difficulty: "athletic",
    durationSeconds: 120,
    thumbnailUrl: thumb("1581009137042-c552e485697a"),
    videoUrl: nativeVideo("advanced conditioning workout plan strength hiit intervals"),
    coachName: "Coach Maya",
    tags: ["advanced plan", "conditioning", "hiit", "athletic"],
    targetMuscles: ["full body", "heart", "legs", "core"],
    caloriesEstimate: 0,
    coachTips: ["Keep HIIT to 1-2 hard days", "Separate hard intervals from heavy leg days when possible"],
    safetyNotes: ["Advanced does not mean maximal every day; recovery drives adaptation"],
    likeCount: 1340
  }),
  video({
    id: "nutrition-protein-30g",
    title: "Build a 30g protein meal",
    category: "Protein tips",
    bodyPart: "Nutrition",
    difficulty: "beginner",
    durationSeconds: 55,
    thumbnailUrl: thumb("1498837167922-ddd27525d352"),
    videoUrl: nativeVideo("30 gram protein meal ideas fitness"),
    coachName: "Coach Jay",
    tags: ["nutrition short", "protein", "meal prep", "muscle"],
    targetMuscles: ["recovery"],
    caloriesEstimate: 0,
    coachTips: ["Start with one palm of lean protein", "Add carbs around training if energy is low"],
    safetyNotes: ["Adjust portions to your calorie goal and dietary needs"],
    relatedFoodId: "chicken-breast",
    likeCount: 2410
  }),
  video({
    id: "nutrition-calorie-deficit-plate",
    title: "Fat-loss plate method",
    category: "Diet tips",
    bodyPart: "Nutrition",
    difficulty: "beginner",
    durationSeconds: 65,
    thumbnailUrl: thumb("1490645935967-10de6ba17061"),
    videoUrl: nativeVideo("fat loss plate method protein vegetables carbs healthy fats"),
    coachName: "Coach Noor",
    tags: ["nutrition short", "calorie deficit", "fat loss"],
    targetMuscles: ["total body"],
    caloriesEstimate: 0,
    coachTips: ["Protein first, vegetables second, carbs and fats matched to your goal"],
    safetyNotes: ["Do not remove entire food groups unless advised by a clinician"],
    likeCount: 2060
  }),
  video({
    id: "nutrition-hydration-training",
    title: "Hydration before training",
    category: "Hydration tips",
    bodyPart: "Hydration",
    difficulty: "beginner",
    durationSeconds: 40,
    thumbnailUrl: thumb("1523362628745-0c100150b504"),
    videoUrl: nativeVideo("hydration before workout electrolytes water tips"),
    coachName: "Coach Eli",
    tags: ["hydration", "performance", "water"],
    targetMuscles: ["performance"],
    caloriesEstimate: 0,
    coachTips: ["Drink steadily before training", "Add electrolytes for long, hot, or high-sweat sessions"],
    safetyNotes: ["Do not force excessive water intake"],
    likeCount: 880
  }),
  video({
    id: "mobility-hips-after-sitting",
    title: "Hip mobility after sitting",
    category: "Mobility",
    bodyPart: "Hips",
    difficulty: "beginner",
    durationSeconds: 180,
    thumbnailUrl: thumb("1552196563-55cd4e45efb3"),
    videoUrl: nativeVideo("hip mobility routine after sitting beginner"),
    coachName: "Coach Maya",
    tags: ["mobility", "hips", "recovery", "desk"],
    targetMuscles: ["hip flexors", "glutes", "lower back"],
    caloriesEstimate: 12,
    coachTips: ["Move slowly", "Breathe into the end range", "Use mobility before lower-body sessions"],
    safetyNotes: ["Avoid sharp pinching in the hip"],
    likeCount: 1040
  }),
  video({
    id: "recovery-sleep-progress",
    title: "Sleep is part of the program",
    category: "Recovery",
    bodyPart: "Recovery",
    difficulty: "beginner",
    durationSeconds: 52,
    thumbnailUrl: thumb("1540206395-68808572332f"),
    videoUrl: nativeVideo("sleep recovery muscle fat loss fitness progress"),
    coachName: "Coach Dan",
    tags: ["recovery", "sleep", "progress"],
    targetMuscles: ["recovery"],
    caloriesEstimate: 0,
    coachTips: ["Aim for a repeatable sleep window", "Hard training works better when recovery is predictable"],
    safetyNotes: ["If fatigue is persistent, reduce intensity and seek professional advice when needed"],
    likeCount: 1710
  }),
  video({
    id: "recovery-foam-roll-warmup",
    title: "Recovery flow for sore legs",
    category: "Recovery",
    bodyPart: "Legs",
    difficulty: "beginner",
    durationSeconds: 300,
    thumbnailUrl: thumb("1576678927484-cc907957088c"),
    videoUrl: nativeVideo("sore legs recovery mobility flow beginner"),
    coachName: "Coach Noor",
    tags: ["recovery", "mobility", "legs"],
    targetMuscles: ["quads", "hamstrings", "glutes", "calves"],
    caloriesEstimate: 20,
    coachTips: ["Keep pressure gentle", "Use recovery days to feel better, not crushed"],
    safetyNotes: ["Do not press directly into painful joints or bruised areas"],
    likeCount: 760
  })
];

fitnessVideos.push(...supplementalMajorCategoryVideos);
