import { FitnessVideo, VideoCategory } from "@/lib/types";

const yt = (query: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
const thumb = (seed: string) => `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=900&q=80`;

export const videoCategories: VideoCategory[] = [
  "Full body",
  "Abs / core",
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Legs",
  "Glutes",
  "Cardio",
  "Mobility",
  "Beginner tips",
  "Diet tips",
  "Protein tips",
  "Hydration tips",
  "Recovery"
];

export const fitnessVideos: FitnessVideo[] = [
  {
    id: "full-body-10-min-beginner",
    title: "10-minute full body starter",
    category: "Full body",
    bodyPart: "Total body",
    difficulty: "beginner",
    durationSeconds: 600,
    thumbnailUrl: thumb("1518611012118-696072aa579a"),
    videoUrl: yt("10 minute beginner full body workout follow along"),
    coachName: "Coach Maya",
    tags: ["beginner", "no equipment", "follow along"],
    caloriesEstimate: 85,
    relatedExerciseId: "bodyweight-squat",
    likeCount: 1240
  },
  {
    id: "core-plank-fix",
    title: "Stop sagging in planks",
    category: "Abs / core",
    bodyPart: "Core",
    difficulty: "beginner",
    durationSeconds: 45,
    thumbnailUrl: thumb("1517964603305-11c0f6f66012"),
    videoUrl: yt("plank form mistakes beginner short"),
    coachName: "Coach Dan",
    tags: ["plank", "form fix", "core"],
    caloriesEstimate: 8,
    relatedExerciseId: "plank",
    likeCount: 890
  },
  {
    id: "chest-push-up-incline",
    title: "Your first clean push-up",
    category: "Chest",
    bodyPart: "Chest",
    difficulty: "beginner",
    durationSeconds: 55,
    thumbnailUrl: thumb("1598971639058-fab3c3109a00"),
    videoUrl: yt("incline push up beginner form"),
    coachName: "Coach Noor",
    tags: ["push-up", "chest", "beginner strength"],
    relatedExerciseId: "push-up",
    likeCount: 730
  },
  {
    id: "back-row-cue",
    title: "Pull with your elbow, not your neck",
    category: "Back",
    bodyPart: "Back",
    difficulty: "beginner",
    durationSeconds: 40,
    thumbnailUrl: thumb("1534367610401-9f5ed68180aa"),
    videoUrl: yt("one arm dumbbell row form elbow to hip"),
    coachName: "Coach Eli",
    tags: ["rows", "posture", "back"],
    relatedExerciseId: "row",
    likeCount: 612
  },
  {
    id: "shoulder-press-ribs",
    title: "Shoulder press without rib flare",
    category: "Shoulders",
    bodyPart: "Shoulders",
    difficulty: "intermediate",
    durationSeconds: 50,
    thumbnailUrl: thumb("1581009137042-c552e485697a"),
    videoUrl: yt("dumbbell shoulder press rib flare fix"),
    coachName: "Coach Maya",
    tags: ["shoulders", "press", "form"],
    relatedExerciseId: "shoulder-press",
    likeCount: 540
  },
  {
    id: "arms-triceps-tip",
    title: "Triceps: elbows stay quiet",
    category: "Arms",
    bodyPart: "Arms",
    difficulty: "beginner",
    durationSeconds: 35,
    thumbnailUrl: thumb("1583454110551-21f2fa2afe61"),
    videoUrl: yt("triceps extension elbow position beginner"),
    coachName: "Coach Jay",
    tags: ["arms", "triceps", "cue"],
    likeCount: 480
  },
  {
    id: "legs-squat-chair",
    title: "Squat to chair: instant form upgrade",
    category: "Legs",
    bodyPart: "Legs",
    difficulty: "beginner",
    durationSeconds: 60,
    thumbnailUrl: thumb("1534438327276-14e5300c3a48"),
    videoUrl: yt("chair squat beginner form"),
    coachName: "Coach Noor",
    tags: ["squat", "legs", "beginner"],
    caloriesEstimate: 18,
    relatedExerciseId: "bodyweight-squat",
    likeCount: 1380
  },
  {
    id: "glutes-bridge-ribs",
    title: "Glute bridge: feel glutes, not back",
    category: "Glutes",
    bodyPart: "Glutes",
    difficulty: "beginner",
    durationSeconds: 52,
    thumbnailUrl: thumb("1571019613454-1cb2f99b2d8b"),
    videoUrl: yt("glute bridge form mistakes lower back"),
    coachName: "Coach Dan",
    tags: ["glutes", "bridge", "back friendly"],
    caloriesEstimate: 10,
    relatedExerciseId: "glute-bridge",
    likeCount: 1020
  },
  {
    id: "cardio-incline-walk",
    title: "Incline walk setup for fat loss",
    category: "Cardio",
    bodyPart: "Heart + legs",
    difficulty: "beginner",
    durationSeconds: 75,
    thumbnailUrl: thumb("1571902943202-507ec2618e8f"),
    videoUrl: yt("incline walking treadmill fat loss beginner"),
    coachName: "Coach Eli",
    tags: ["incline walk", "fat loss", "zone 2"],
    caloriesEstimate: 180,
    relatedExerciseId: "treadmill-incline-walk",
    likeCount: 2210
  },
  {
    id: "mobility-hips-reset",
    title: "Hip reset after sitting",
    category: "Mobility",
    bodyPart: "Hips",
    difficulty: "beginner",
    durationSeconds: 90,
    thumbnailUrl: thumb("1552196563-55cd4e45efb3"),
    videoUrl: yt("hip mobility routine after sitting beginner"),
    coachName: "Coach Maya",
    tags: ["mobility", "hips", "recovery"],
    likeCount: 660
  },
  {
    id: "beginner-mistakes",
    title: "3 beginner workout mistakes",
    category: "Beginner tips",
    bodyPart: "All",
    difficulty: "beginner",
    durationSeconds: 65,
    thumbnailUrl: thumb("1517836357463-d25dfeac3438"),
    videoUrl: yt("beginner workout mistakes form recovery nutrition"),
    coachName: "Coach Dan",
    tags: ["beginner", "mistakes", "consistency"],
    likeCount: 1870
  },
  {
    id: "diet-deficit-no-spot",
    title: "Belly fat truth in 45 seconds",
    category: "Diet tips",
    bodyPart: "Nutrition",
    difficulty: "beginner",
    durationSeconds: 45,
    thumbnailUrl: thumb("1490645935967-10de6ba17061"),
    videoUrl: yt("belly fat spot reduction myth calorie deficit"),
    coachName: "Coach Noor",
    tags: ["fat loss", "calorie deficit", "no spot reduction"],
    likeCount: 2450
  },
  {
    id: "protein-30g-meal",
    title: "Build a 30g protein meal",
    category: "Protein tips",
    bodyPart: "Nutrition",
    difficulty: "beginner",
    durationSeconds: 50,
    thumbnailUrl: thumb("1498837167922-ddd27525d352"),
    videoUrl: yt("30 gram protein meal ideas fitness"),
    coachName: "Coach Jay",
    tags: ["protein", "meal prep", "muscle"],
    relatedFoodId: "chicken-breast",
    likeCount: 1980
  },
  {
    id: "hydration-before-workout",
    title: "Hydrate before you train",
    category: "Hydration tips",
    bodyPart: "Hydration",
    difficulty: "beginner",
    durationSeconds: 35,
    thumbnailUrl: thumb("1523362628745-0c100150b504"),
    videoUrl: yt("hydration before workout tips"),
    coachName: "Coach Eli",
    tags: ["hydration", "water", "performance"],
    likeCount: 510
  },
  {
    id: "recovery-sleep-wins",
    title: "Sleep is part of the plan",
    category: "Recovery",
    bodyPart: "Recovery",
    difficulty: "beginner",
    durationSeconds: 55,
    thumbnailUrl: thumb("1540206395-68808572332f"),
    videoUrl: yt("sleep recovery muscle fat loss fitness"),
    coachName: "Coach Maya",
    tags: ["sleep", "recovery", "progress"],
    likeCount: 1320
  }
];
