alter table public.profiles enable row level security;
alter table public.meal_days enable row level security;
alter table public.meals enable row level security;
alter table public.workout_logs enable row level security;
alter table public.progress_entries enable row level security;
alter table public.workouts enable row level security;
alter table public.exercises enable row level security;
alter table public.workout_programs enable row level security;
alter table public.exercise_library enable row level security;
alter table public.nutrition_foods enable row level security;
alter table public.user_custom_foods enable row level security;
alter table public.favorite_foods enable row level security;
alter table public.meal_templates enable row level security;
alter table public.micronutrients enable row level security;
alter table public.food_logs enable row level security;
alter table public.hydration_logs enable row level security;
alter table public.hydration_adjustments enable row level security;
alter table public.user_state_snapshots enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Admins can read profiles" on public.profiles;
drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id and role = 'user');
create policy "Admins can read profiles" on public.profiles for select using (public.is_admin());
create policy "Admins can manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Users can manage own meal days" on public.meal_days;
drop policy if exists "Users can read own meals" on public.meals;
drop policy if exists "Users can manage own logs" on public.workout_logs;
drop policy if exists "Users can manage own progress" on public.progress_entries;
drop policy if exists "Users can manage own custom foods" on public.user_custom_foods;
drop policy if exists "Users can manage own favorite foods" on public.favorite_foods;
drop policy if exists "Users can manage own food logs" on public.food_logs;
drop policy if exists "Users can manage own hydration logs" on public.hydration_logs;
drop policy if exists "Users can manage own hydration adjustments" on public.hydration_adjustments;
drop policy if exists "Users can manage own state snapshots" on public.user_state_snapshots;
create policy "Users can manage own meal days" on public.meal_days for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can read own meals" on public.meals for select using (exists (select 1 from public.meal_days where public.meal_days.id = meal_day_id and public.meal_days.user_id = auth.uid()));
create policy "Users can manage own logs" on public.workout_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own progress" on public.progress_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own custom foods" on public.user_custom_foods for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own favorite foods" on public.favorite_foods for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own food logs" on public.food_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own hydration logs" on public.hydration_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own hydration adjustments" on public.hydration_adjustments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage own state snapshots" on public.user_state_snapshots for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Anyone can read seed workouts" on public.workouts;
drop policy if exists "Anyone can read seed exercises" on public.exercises;
drop policy if exists "Anyone can read workout programs" on public.workout_programs;
drop policy if exists "Anyone can read exercise library" on public.exercise_library;
drop policy if exists "Anyone can read nutrition foods" on public.nutrition_foods;
drop policy if exists "Anyone can read meal templates" on public.meal_templates;
drop policy if exists "Anyone can read micronutrients" on public.micronutrients;
create policy "Anyone can read seed workouts" on public.workouts for select using (true);
create policy "Anyone can read seed exercises" on public.exercises for select using (true);
create policy "Anyone can read workout programs" on public.workout_programs for select using (true);
create policy "Anyone can read exercise library" on public.exercise_library for select using (true);
create policy "Anyone can read nutrition foods" on public.nutrition_foods for select using (true);
create policy "Anyone can read meal templates" on public.meal_templates for select using (true);
create policy "Anyone can read micronutrients" on public.micronutrients for select using (true);

drop policy if exists "Admins can manage workouts" on public.workouts;
drop policy if exists "Admins can manage exercises" on public.exercises;
drop policy if exists "Admins can manage workout programs" on public.workout_programs;
drop policy if exists "Admins can manage exercise library" on public.exercise_library;
drop policy if exists "Admins can manage nutrition foods" on public.nutrition_foods;
create policy "Admins can manage workouts" on public.workouts for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage exercises" on public.exercises for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage workout programs" on public.workout_programs for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage exercise library" on public.exercise_library for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins can manage nutrition foods" on public.nutrition_foods for all using (public.is_admin()) with check (public.is_admin());
